model: Server #Server #Whisper 
py_port: 9310
use_wake_flag: 1
gui_port: 9120
face_recog: True
audio_auth: False
face_recog_api: http://128.205.43.183:5001/face_recog
transcribe_api: http://128.205.43.183:5001/transcribe
audio_recog: False
audio_authen_api: http://128.205.43.183:5001/audio_recog
audio_authe_user: ninad
ip: 10.0.255.8
port: 9559
